version: "3.7"

services:
  pg-database:
    container_name: postgres
    image: debezium/postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  openvidu-service:
    container_name: openvidu-service
    image: openvidu/openvidu-server-kms
    environment:
      - OPENVIDU_SECRET=MY_SECRET
    ports:
      - 4443:4443
