version: "3.7"

services:
  pg-database:
    container_name: postgres
    image: debezium/postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure
    networks:
      enviroment:

  openvidu-service:
    container_name: openvidu-service
    image: openvidu/openvidu-server-kms
    environment:
      - OPENVIDU_SECRET=MY_SECRET
    ports:
      - 4443:4443

  rabbitmq:
    container_name: rabbitmq
    image: uuhnaut69/rabbitmq
    ports:
      - 5672:5672
      - 25672:25672
      - 15672:15672
      - 15674:15674
      - 61613:61613
    networks:
      enviroment:

networks:
  enviroment:
