spring:
  application:
    name: video-conference-app
  banner:
    location: classpath:banner.txt
  datasource:
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATA_SOURCE_USERNAME}
    password: ${SPRING_DATA_SOURCE_PASSWORD}
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
jwt:
  secret-key: video-conference-app
  token-validity-in-seconds: 86400000

openvidu:
  hostname: ${OPENVIDU_HOSTNAME}
  secret: ${OPENVIDU_SECRET}

rabbitmq:
  host: ${RABBIT_HOST}
  port: ${RABBIT_PORT}
  username: ${RABBIT_USERNAME}
  password: ${RABBIT_PASSWORD}
